version: "2"
run:
  build-tags:
    - githooks
    - integration
linters:
  enable:
    - asciicheck
    - errname
    - gochecknoinits
    - gocritic
    - gocyclo
    - godox
    - misspell
    - testifylint
  settings:
    goconst:
      min-len: 3
      min-occurrences: 4
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    testifylint:
      disable:
        - require-error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
