---
name: Run integration tests

on:
  workflow_call:

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: make setup-tools

      - name: Start PostgreSQL cluster
        run: docker compose -f .github/integration-docker-compose.yml --project-directory ${{ github.workspace }} up -d --wait

      - name: Integration tests
        run: make test-integration

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-int
          path: coverage-int.*

      - name: Cleanup PostgreSQL cluster
        if: always()
        run: docker compose -f .github/integration-docker-compose.yml --project-directory ${{ github.workspace }} down -v --remove-orphans
