---
name: Run integration tests

on:
  workflow_call:

jobs:
  test-integration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 15432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: make setup-tools

      - name: Integration tests
        run: make test-integration

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-int
          path: coverage-int.*
